config/routes.rb
Rails.application.routes.draw do
  #get 'user/login'

  resources :articles do
    resources :comments
  end

  resources :users
  resources :sessions

  post "/" => "sessions#require_login"
  get "/logout" => "sessions#logout"

  root 'users#login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :require_login

  def index
    @session = session
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end

  def require_login
    sessions_ctrl = SessionsController.new(@_request)
    if !sessions_ctrl.is_logged_in
      flash[:error] = "You must be logged in to access this section"
      redirect_to "/"
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "rob", password: "abc", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/sessions_controller.rb
require 'rubygems'
require 'net-ldap'

class SessionsController < ApplicationController

  def initialize(req = nil)
    if req != nil
      @_request = req
    end
  end

  def show
  end

  def check_auth
    if !is_logged_in
      redirect_to "/"
    end
  end

  def is_logged_in
    if session.has_key?("current_user_id")
      return true
    else
      return false
    end
  end

  def login
    if is_logged_in
      @user = User.find(session[:current_user_id])
      redirect_to "/users/#{@user.id}"
    else
      redirect_to "/"
    end
  end

  def logout
    session.delete(:current_user_id)
    redirect_to "/"
  end

  def require_login
    if !is_logged_in
      @user = authenticate(params[:username], params[:password])
      if @user == nil
        session.delete(:current_user_id)
        redirect_to :controller => 'users', :action => 'login', :alert => "Invalid username or password"
      else
        session[:username] = @user.username
        session[:password] = params[:password]
        session[:current_user_id] = @user.id
        redirect_to @user
      end
    end
  end

  def authenticate(username, password)
    @username = username
    @password = password

    @connection = nil
    @host = "thematrix.robtcallahan.net"
    @port = 389
    @domain =  "thematrix.robtcallahan.net"
    @treebase = 'cn=Users,dc=thematrix,dc=robtcallahan,dc=net'

    ldap = Net::LDAP.new(:host => @host, :port => @port)
    ldap.auth("#{@username}@#{@domain}", @password)

    # ldap.bind is false if username/password are bad
    if ldap.bind
      filter = Net::LDAP::Filter.eq("sAMAccountName", @username)

      @user = User.new
      if User.exists?(username: @username)
        @user = User.where(username: "#{@username}").first
        @user.update(mail: @user.mail)
        return @user
      end

      entries = ldap.search(:base => @treebase, :filter => filter, :attributes => ['samaccountname','givenname','sn','lastLogon','mail','memberOf'])
      entry = entries[0]

      @user = User.new
      @user.username = entry.samaccountname[0]
      @user.firstname = entry.givenname[0]
      @user.lastname = entry.sn[0]
      @user.mail = entry.mail[0]

      entry.each do |attribute, values|
        if attribute.match(/memberof/)
          values.each do |value|
            a = value.split(',')
            md = a[0].match(/CN=(.+)/)
            @user.group = md[1]
          end
        end
      end
      @user.save
      return @user
    else
      return nil
    end
  end
end

app/controllers/users_controller.rb
require 'net-ldap'
require 'date'

class UsersController < ApplicationController
  AD_EPOCH      = 116_444_736_000_000_000
  AD_MULTIPLIER = 10_000_000

  before_action :require_login, except: [:login]

  def login
    @error_msg = params[:alert]
  end

  def index
    @session = session
    @connection = nil
    @host = "thematrix.robtcallahan.net"
    @port = 389
    @domain =  "thematrix.robtcallahan.net"

    ldap = Net::LDAP.new(:host => @host, :port => @port)
    ldap.auth("#{session[:username]}@#{@domain}", session[:password])

    # ldap.bind is false if username/password are bad
    if ldap.bind
      @treebase = 'cn=Users,dc=thematrix,dc=robtcallahan,dc=net'
      filter = Net::LDAP::Filter.ge("sn", " ")

      @entries = ldap.search(:base => @treebase, :filter => filter, :attributes => ['sAMAccountName','givenName','sn','lastlogon','mail','memberOf'])
      i = 0
      for entry in @entries
        time = @entries[i][:lastlogon][0]
        if "XX#{time}XX" == "XX0XX"
          @entries[i][:lastlogon][0] = "-"
        else
          @entries[i][:lastlogon][0] = ad2time(time)
        end
        i = i + 1
      end
    else
      # some error here
    end
  end

  def show
    @user = User.find(session[:current_user_id])
  end

  private

  def require_login
    sessions_ctrl = SessionsController.new(@_request)
    if !sessions_ctrl.is_logged_in
      flash[:error] = "You must be logged in to access this section"
      redirect_to "/"
    end
  end

  # convert from AD's time string to a Time object
  def ad2time(time)
    Time.at((time.to_i - AD_EPOCH) / AD_MULTIPLIER)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/articles/_header.html.erb
<div style="background:darkblue; color:white; width:100%; height:50px; margin-bottom:20px;">
  <div style="font-size:16pt; position:absolute; width:100px; left:45%; top:20px; text-align:center;">My Blog</div>
</div>

app/views/articles/edit.html.erb
<%= render 'header' %>

<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= render 'header' %>

<h1>Listing articles</h1>

<%= link_to 'New article', new_article_path %>
<br><br>

<table>
  <tr>
    <th width=100>Title</th>
    <th width=20>&nbsp;</th>
    <th>Text</th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td width=20>&nbsp;</td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Users', users_path %>
<%= link_to 'My Account', "/users/#{@session[:current_user_id]}" %>
<%= link_to 'Logout', "/logout" %>

app/views/articles/new.html.erb
<%= render 'header' %>

<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= render 'header' %>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ]) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/_header.html.erb
<div style="background:darkblue; color:white; width:100%; height:50px; margin-bottom:20px;">
  <div style="font-size:16pt; position:absolute; width:100px; left:45%; top:20px; text-align:center;">My Blog</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_header.html.erb
<div style="background:darkblue; color:white; width:100%; height:50px; margin-bottom:20px;">
  <div style="font-size:16pt; position:absolute; width:100px; left:45%; top:20px; text-align:center;">My Blog</div>
</div>

app/views/users/index.html.erb
<%= render 'header' %>

<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 10px;
}</style>

<p>
  <h1>Users</h1>
  <br>
  <p>
    <table>
      <tr>
        <td>First Name</td>
        <td>Last Name</td>
        <td>User Name</td>
        <td>EMail</td>
        <td>Last Login</td>
      </tr>
      <% @entries.each do |user| %>
        <tr>
          <td><%= user[:givenName][0] %></td>
          <td><%= user[:sn][0] %></td>
          <td><%= user[:sAMAccountName][0] %></td>
          <td><%= user[:mail][0] %></td>
          <td><%= user[:lastlogon][0] %></td>
        </tr>
      <%end %>
    </table>
  </p>
  <%= link_to 'Articles', articles_path %>
  <%= link_to 'My Account', "/users/#{@session[:current_user_id]}" %>
  <%= link_to 'Logout', "/logout" %>
</p>

app/views/users/login.html.erb
<%= render 'header' %>

<h1>Login</h1>

<h2 style="color: red"><%= @error_msg %></h2>

<%= form_with model: @user, local: true do |form| %>

  <p>
    <%= form.label :User %><br>
    <%= form.text_field :username %>
  </p>

  <p>
    <%= form.label :Password %><br>
    <%= form.password_field :password %>
  </p>

  <p>
    <%= form.submit "Login" %>
  </p>

<% end %>

app/views/users/show.html.erb
<%= render 'header' %>

<p>
  <h1>My Account</h1>
  <br>
  <p>
    <table>
      <tr><td><b>Attribute</b></td><td><b>Value</b></td></tr>
      <tr><td>First Name</td><td><%= @user.firstname %></td></tr>
      <tr><td>Last Name</td><td><%= @user.lastname %></td></tr>
      <tr><td>User Name</td><td><%= @user.username %></td></tr>
      <tr><td>EMail</td><td><%= @user.mail %></td></tr>
      <tr><td>Group</td><td><%= @user.group %></td></tr>
      <tr><td>Last Login</td><td><%= @user.updated_at %></td></tr>
    </table>
  </p>
  <%= link_to 'Users', users_path %>
  <%= link_to 'Articles', articles_path %>
  <%= link_to 'Logout', "/logout" %>
</p>

app/views/welcome/index.html.erb
<h1>Hello, Rails</h1>
<%= link_to 'My Blog', controller: 'articles' %>